version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The LEADSPLUS_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     LEADSPLUS_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"    # Important: In a production environment your should remove the external port


  nosql.data:
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port


  rabbitmq:
    ports:
      - "15673:15673"  # Important: In a production environment your should remove the external port
      - "5673:5673"    # Important: In a production environment your should remove the external port

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AdminPortalClient=http://${LEADSPLUS_PROD_ADMIN_PORTAL_DOMAIN}:5104
      - ConnectionString=${LEADSPLUS_AZURE_IDENTITY_DB:-Server=sql.data;Database=LeadsPlus.IdentityDb;User Id=sa;Password=Pass@word}       
      - AgentApiClient=http://${LEADSPLUS_PROD_AGENT_API_DOMAIN}:5109
      - InqueryHistoryApiClient=http://${LEADSPLUS_PROD_AGENT_API_DOMAIN}:5106
      - ContactApiClient=http://${LEADSPLUS_PROD_CONTACT_API_DOMAIN}:5102
      - CloudMailinApiClient=http://${LEADSPLUS_PROD_CLOUDMAILIN_API_DOMAIN}:5109
      - EmailSenderApiClient=http://${LEADSPLUS_PROD_EMAILSENDER_API_DOMAIN}:5109
      - UseCustomizationData=False  
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5105:80"   

  agent.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${LEADSPLUS_AZURE_COSMOSDB:-mongodb://nosql.data}
      - Database=AgentStore
      - identityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110. 
      - IdentityUrlExternal=http://${LEADSPLUS_PROD_IDENTITY_API_DOMAIN}:5105
      - EventBusConnection=${LEADSPLUS_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${LEADSPLUS_SERVICE_BUS_USERNAME}
      - EventBusPassword=${LEADSPLUS_SERVICE_BUS_PASSWORD}          
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5109:80"   # Important: In a production environment your should remove the external port (5109) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  inqueryhistory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - DatabaseConnectionString=${LEADSPLUS_AZURE_COSMOSDB:-mongodb://nosql.data}
      - DatabaseName=InqueryHistoryStore
      - identityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110. 
      - IdentityUrlExternal=http://${LEADSPLUS_PROD_IDENTITY_API_DOMAIN}:5105
      - EventBusConnection=${LEADSPLUS_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${LEADSPLUS_SERVICE_BUS_USERNAME}
      - EventBusPassword=${LEADSPLUS_SERVICE_BUS_PASSWORD}          
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5106:80"   # Important: In a production environment your should remove the external port (5109) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  contact.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - DatabaseConnectionString=${LEADSPLUS_AZURE_COSMOSDB:-mongodb://nosql.data}
      - DatabaseName=ContactStore
      - identityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - IdentityUrlExternal=http://${LEADSPLUS_PROD_IDENTITY_API_DOMAIN}:5105
      - EventBusConnection=${LEADSPLUS_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${LEADSPLUS_SERVICE_BUS_USERNAME}
      - EventBusPassword=${LEADSPLUS_SERVICE_BUS_PASSWORD}          
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5102:80"   # Important: In a production environment your should remove the external port (5102) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  webstatus.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80     
      - IdentityUrl=http://identity.api/hc
      - AgentUrl=http://Agent.API/hc
      - ContactUrl=http://Contact.API/hc
      - InquiryHistoryUrl=http://InquiryHistory.API/hc
      - CloudmailinWebhook=http://cloudmailin.webhook/hc
      - AdminPortal=http://webspa/hc
      - EmailSenderBackgroundTask=http://emailsender/hc
      - EmailParserBackgroundTask=http://emailparsar/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5107:80"

  admin.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://${LEADSPLUS_PROD_IDENTITY_API_DOMAIN}:5105              #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - AgentUrl=http://${LEADSPLUS_PROD_AGENT_API_DOMAIN}:5109
      - ContactUrl=http://${LEADSPLUS_PROD_CONTACT_API_DOMAIN}:5102
      - InquiryHistoryUrl=http://${LEADSPLUS_PROD_INQUIRY_HISTORY_API_DOMAIN}:5106
      - IdentityUrlHC=http://identity.api/hc     #Local: Use ${LEADSPLUS_PROD_EXTERNAL_DNS_NAME_OR_IP}, if using external IP or DNS name from browser.          
      - AgentUrlHC=http://agent.api/hc
      - ContactUrlHC=http://contact.api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - SignalrHubUrl=http://${LEADSPLUS_PROD_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5104:80"

  cloudmailin.webhook:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${LEADSPLUS_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${LEADSPLUS_SERVICE_BUS_USERNAME}
      - EventBusPassword=${LEADSPLUS_SERVICE_BUS_PASSWORD}          
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5108:80"

  emailsender.backgroundtask:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${LEADSPLUS_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${LEADSPLUS_SERVICE_BUS_USERNAME}
      - EventBusPassword=${LEADSPLUS_SERVICE_BUS_PASSWORD}     
      - SendgridApiKey= ${LEADSPLUS_SENDGRID_APP_KEY}
      - SendgridMailingApi= ${LEADSPLUS_SENDGRID_MAILING_URL}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5110:80"

  emailparsar.backgroundtask:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${LEADSPLUS_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${LEADSPLUS_SERVICE_BUS_USERNAME}
      - EventBusPassword=${LEADSPLUS_SERVICE_BUS_PASSWORD}     
      - SendgridApiKey= ${LEADSPLUS_SENDGRID_APP_KEY}
      - SendgridMailingApi= ${LEADSPLUS_SENDGRID_MAILING_URL}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5111:80"